### ISSUE TITLE
Fix some issues

### ISSUE THREAD

**Issue by alifurkanbudak** [muratekici/snek#2]
- [x] Food spawning at the same location(Work on random numbers) - AFB
- [ ] Scoreboard - Muro
- [x] User's own color should be fixed - Muro
- [x] Snakes' initial direction should be random - AFB
- [x] Snakes shouldn't turn opposite direction - Muro
- [x] After dying UI should stay for a while - Muro
- [x] Fix crash error - AFB

**Comment by lighterm** [comment]
sardiii
